#!/bin/bash
#
# setup-android-signing.sh - Set up Android release signing for Ballee
#
# This script guides you through creating a release keystore and
# configuring key.properties for Android release builds.
#
# Usage:
#   ./setup-android-signing.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
ANDROID_DIR="$REPO_ROOT/apps/mobile/android"
KEY_PROPS="$ANDROID_DIR/key.properties"
BUILD_GRADLE="$ANDROID_DIR/app/build.gradle.kts"

echo "==========================================="
echo "Ballee Android Signing Setup"
echo "==========================================="
echo ""

# Check if key.properties already exists
if [ -f "$KEY_PROPS" ]; then
    echo "key.properties already exists at:"
    echo "  $KEY_PROPS"
    echo ""
    read -p "Do you want to overwrite it? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi
fi

echo "This script will help you set up release signing for Android."
echo ""
echo "You have two options:"
echo "  1. Create a new keystore"
echo "  2. Use an existing keystore"
echo ""
read -p "Choose option (1/2): " -n 1 -r OPTION
echo ""

KEYSTORE_PATH=""
KEYSTORE_PASSWORD=""
KEY_ALIAS=""
KEY_PASSWORD=""

if [ "$OPTION" = "1" ]; then
    # Create new keystore
    echo ""
    echo "Creating a new release keystore..."
    echo ""

    # Default keystore location
    DEFAULT_KEYSTORE="$HOME/ballee-release-key.jks"
    read -p "Keystore path [$DEFAULT_KEYSTORE]: " KEYSTORE_PATH
    KEYSTORE_PATH="${KEYSTORE_PATH:-$DEFAULT_KEYSTORE}"

    # Check if file already exists
    if [ -f "$KEYSTORE_PATH" ]; then
        echo "ERROR: File already exists at $KEYSTORE_PATH"
        echo "Please choose a different path or delete the existing file."
        exit 1
    fi

    # Key alias
    read -p "Key alias [ballee]: " KEY_ALIAS
    KEY_ALIAS="${KEY_ALIAS:-ballee}"

    # Passwords
    echo ""
    echo "Enter keystore password (min 6 characters):"
    read -s KEYSTORE_PASSWORD
    echo ""
    echo "Enter key password (press Enter to use same as keystore):"
    read -s KEY_PASSWORD
    KEY_PASSWORD="${KEY_PASSWORD:-$KEYSTORE_PASSWORD}"
    echo ""

    if [ ${#KEYSTORE_PASSWORD} -lt 6 ]; then
        echo "ERROR: Password must be at least 6 characters."
        exit 1
    fi

    # Create the keystore
    echo "Creating keystore..."
    keytool -genkey -v \
        -keystore "$KEYSTORE_PATH" \
        -keyalg RSA \
        -keysize 2048 \
        -validity 10000 \
        -alias "$KEY_ALIAS" \
        -storepass "$KEYSTORE_PASSWORD" \
        -keypass "$KEY_PASSWORD" \
        -dname "CN=Ballee, OU=Mobile, O=Ballee, L=Unknown, ST=Unknown, C=US"

    echo ""
    echo "Keystore created at: $KEYSTORE_PATH"

elif [ "$OPTION" = "2" ]; then
    # Use existing keystore
    echo ""
    echo "Using an existing keystore..."
    echo ""

    read -p "Keystore path: " KEYSTORE_PATH

    if [ ! -f "$KEYSTORE_PATH" ]; then
        echo "ERROR: Keystore not found at $KEYSTORE_PATH"
        exit 1
    fi

    read -p "Key alias: " KEY_ALIAS

    echo "Enter keystore password:"
    read -s KEYSTORE_PASSWORD
    echo ""

    echo "Enter key password (press Enter if same as keystore):"
    read -s KEY_PASSWORD
    KEY_PASSWORD="${KEY_PASSWORD:-$KEYSTORE_PASSWORD}"
    echo ""

    # Verify the keystore
    echo "Verifying keystore..."
    if ! keytool -list -keystore "$KEYSTORE_PATH" -alias "$KEY_ALIAS" -storepass "$KEYSTORE_PASSWORD" > /dev/null 2>&1; then
        echo "ERROR: Could not verify keystore. Check path, alias, and password."
        exit 1
    fi
    echo "Keystore verified."

else
    echo "Invalid option."
    exit 1
fi

# Create key.properties
echo ""
echo "Creating key.properties..."

cat > "$KEY_PROPS" << EOF
# Android release signing configuration
# Generated by setup-android-signing.sh on $(date)
#
# IMPORTANT: Do NOT commit this file to git!
# It is already in .gitignore.

storePassword=$KEYSTORE_PASSWORD
keyPassword=$KEY_PASSWORD
keyAlias=$KEY_ALIAS
storeFile=$KEYSTORE_PATH
EOF

echo "Created: $KEY_PROPS"

# Check if signing config is enabled in build.gradle.kts
echo ""
echo "Checking build.gradle.kts..."

if grep -q "// signingConfigs" "$BUILD_GRADLE"; then
    echo ""
    echo "NOTE: Signing config is still commented out in build.gradle.kts"
    echo ""
    echo "To enable release signing, uncomment these sections in:"
    echo "  $BUILD_GRADLE"
    echo ""
    echo "1. Uncomment signingConfigs block:"
    echo '   signingConfigs {'
    echo '       create("release") {'
    echo '           ...'
    echo '       }'
    echo '   }'
    echo ""
    echo "2. In buildTypes.release, change:"
    echo '   signingConfig = signingConfigs.getByName("debug")'
    echo "   to:"
    echo '   signingConfig = signingConfigs.getByName("release")'
else
    echo "Signing config appears to be enabled."
fi

# Summary
echo ""
echo "==========================================="
echo "Setup Complete"
echo "==========================================="
echo ""
echo "Keystore: $KEYSTORE_PATH"
echo "Key alias: $KEY_ALIAS"
echo "Config: $KEY_PROPS"
echo ""
echo "IMPORTANT:"
echo "  1. Back up your keystore file securely!"
echo "     If you lose it, you cannot update your app on Play Store."
echo ""
echo "  2. key.properties contains passwords - keep it secure!"
echo "     It is already in .gitignore."
echo ""
echo "  3. For CI/CD, store these values as secrets."
echo ""
echo "Next steps:"
echo "  1. Enable signing in build.gradle.kts (if not done)"
echo "  2. Test with: flutter build apk --release"
echo "==========================================="
